### ISSUE TITLE
App not shoing up in share feature when using Firefox

### ISSUE THREAD

**Issue by TheFitzZZ** [acez/bookmark-companion#24]
Hi! 

I've bought and successfully configured the app on my iPhone and was able to sync my test bookmarks successfully. 

This may not be an issue with the app, but I don't see it in the list to share a link towards with Firefox. I see it with Edge, Safari & Chrome, and it is not hidden in the list when I manually set what apps to show and what not. 

Any pointers? 

Thanks!

**Comment by acez** [comment]
Hey,

thank you very much for your support. I was able to reproduce that behavior -  it might be related to the NSExtensionActivationRule in the share extension. I will take care and see how this is fixable.
Thanks again for finding & reporting that issue.

**Comment by acez** [comment]
Hi,

I could successfully point the issue to the NSExtensionActivationRule.
Seems like Firefox does not only send an attachment of type "public.url" but also additionally one of type "public.plain-text". I have updated the NSExtensionActivationRule of the Share Extension to be visible as soon as there is one url shared by the host app, regardless of other shared attachments. See commit 10ef6ad0cc144d477a3f52cad9d6094fa88c69ba.

I have already uploaded a new Version 1.2.1 to the AppStore waiting for a review by Apple.
I will let this issue open until the new version is released on the AppStore - would be cool if you can confirm if that fixes the issue for you then. Thank you :smiley:

**Comment by TheFitzZZ** [comment]
Will do once updated, thank you for the swift change!

**Comment by acez** [comment]
Version 1.2.1 is now approved by Apple and available at the AppStore.

**Comment by TheFitzZZ** [comment]
Can confirm, thank you very much!
