### ISSUE TITLE
Bookmark sorting

### ISSUE THREAD

**Issue by sebw** [acez/bookmark-companion#4]
It looks like bookmarks are currently sorted by URL alphabetically. For example the first bookmark is an FTP link bookmarked in 2011 :D 

Would it be possible to allow sorting per most recent and also oldest?

Thanks!

**Comment by acez** [comment]
Sounds good. I will rework the components a bit with #1 and will add options to sort bookmarks. 
Maybe even the possibility to sort ascending and descending for created and also modified date.

**Comment by acez** [comment]
Sorting is now in the main branch and will be part of the next AppStore release. Just fixing some minor issues. :-)
