### ISSUE TITLE
Tag search when creating a bookmark

### ISSUE THREAD

**Issue by sebw** [acez/bookmark-companion#5]
When creating a bookmark, we have to scroll through the list of tags.

Searching and autocompletion for tags would be nice.

If tag is not found, I would expect the tag to be created.

Thanks!

**Comment by acez** [comment]
Also I would like to implement #1 first and then get to this.

**Comment by acez** [comment]
Version 1.3.0, which includes this feature, is now available on the AppStore.

Thanks for your suggestion  :smiley:
